# PDF Generator for Basic Reports
# Converts basic markdown to PDF

param(
    [string]$MarkdownFile = "Terraform_Plan_Basic_Report.md"
)

# Generate timestamp
$timestamp = Get-Date -Format "ddMMyyyyHHmmss"

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Basic Report PDF Generator" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# File paths
$htmlFile = "Terraform_Plan_Basic_Report_$timestamp.html"
$pdfFile = "Terraform_Plan_Basic_Report_$timestamp.pdf"

# Check if markdown file exists
if (-not (Test-Path $MarkdownFile)) {
    Write-Host "ERROR: Markdown file not found: $MarkdownFile" -ForegroundColor Red
    exit 1
}

Write-Host "Reading markdown file..." -ForegroundColor Yellow

# Read markdown content
$markdownContent = Get-Content $MarkdownFile -Raw

# Simple markdown to HTML conversion (basic)
$htmlContent = $markdownContent

# Convert markdown headers
$htmlContent = $htmlContent -replace '# (.+)', '<h1>$1</h1>'
$htmlContent = $htmlContent -replace '## (.+)', '<h2>$1</h2>'
$htmlContent = $htmlContent -replace '### (.+)', '<h3>$1</h3>'

# Convert bold and italic
$htmlContent = $htmlContent -replace '\*\*(.+?)\*\*', '<strong>$1</strong>'
$htmlContent = $htmlContent -replace '\*(.+?)\*', '<em>$1</em>'

# Convert inline code
$htmlContent = $htmlContent -replace '`([^`]+)`', '<code>$1</code>'

# Convert code blocks
$htmlContent = $htmlContent -replace '``````([^`]+)``````', '<pre><code>$1</code></pre>'

# Convert horizontal rules
$htmlContent = $htmlContent -replace '---', '<hr>'

# Convert line breaks
$htmlContent = $htmlContent -replace "`n", '<br>'

# Create full HTML with styling
$html = @"
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Terraform Plan Report - Basic</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            max-width: 1200px;
            margin: 0 auto;
            padding: 40px;
            background: #f5f5f5;
        }
        .container {
            background: white;
            padding: 40px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        h1 {
            color: #2c3e50;
            border-bottom: 3px solid #3498db;
            padding-bottom: 10px;
            font-size: 32px;
        }
        h2 {
            color: #34495e;
            border-bottom: 2px solid #95a5a6;
            padding-bottom: 8px;
            margin-top: 30px;
            font-size: 24px;
        }
        h3 {
            color: #555;
            margin-top: 20px;
            font-size: 18px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
        }
        th, td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }
        th {
            background-color: #3498db;
            color: white;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        code {
            background-color: #f4f4f4;
            padding: 2px 6px;
            border-radius: 3px;
            font-family: 'Courier New', monospace;
            font-size: 14px;
        }
        pre {
            background-color: #2c3e50;
            color: #ecf0f1;
            padding: 15px;
            border-radius: 5px;
            overflow-x: auto;
            font-family: 'Courier New', monospace;
            font-size: 13px;
        }
        pre code {
            background-color: transparent;
            color: #ecf0f1;
            padding: 0;
        }
        hr {
            border: none;
            border-top: 2px solid #ecf0f1;
            margin: 30px 0;
        }
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 2px solid #ecf0f1;
            text-align: center;
            color: #7f8c8d;
            font-size: 12px;
        }
        .badge {
            display: inline-block;
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 12px;
            font-weight: bold;
            margin-right: 5px;
        }
        .badge-basic {
            background-color: #95a5a6;
            color: white;
        }
    </style>
</head>
<body>
    <div class="container">
        <div style="text-align: right; margin-bottom: 20px;">
            <span class="badge badge-basic">BASIC REPORT - NO AI</span>
        </div>
        $htmlContent
        <div class="footer">
            <p>Generated by Terraform Plan Basic Parser | No AI Analysis</p>
        </div>
    </div>
</body>
</html>
"@

Write-Host "Creating HTML file..." -ForegroundColor Yellow

# Save HTML file
$html | Out-File -FilePath $htmlFile -Encoding UTF8

Write-Host "✓ HTML file created: $htmlFile" -ForegroundColor Green
Write-Host ""

# Convert to PDF using Chrome
Write-Host "Converting to PDF..." -ForegroundColor Yellow

# Find Chrome executable
$chromePaths = @(
    "C:\Program Files\Google\Chrome\Application\chrome.exe",
    "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
    "$env:LOCALAPPDATA\Google\Chrome\Application\chrome.exe"
)

$chromePath = $null
foreach ($path in $chromePaths) {
    if (Test-Path $path) {
        $chromePath = $path
        break
    }
}

if (-not $chromePath) {
    Write-Host "ERROR: Chrome not found. Please install Google Chrome." -ForegroundColor Red
    Write-Host "HTML file saved: $htmlFile" -ForegroundColor Yellow
    exit 1
}

Write-Host "Using Chrome: $chromePath" -ForegroundColor Cyan

# Convert HTML to PDF
$htmlFullPath = (Resolve-Path $htmlFile).Path
$pdfFullPath = Join-Path (Get-Location) $pdfFile

# Use Start-Process to better handle Chrome
$chromeArgs = @(
    "--headless"
    "--disable-gpu"
    "--no-sandbox"
    "--print-to-pdf=`"$pdfFullPath`""
    "file:///$($htmlFullPath -replace '\\', '/')"
)

$process = Start-Process -FilePath $chromePath -ArgumentList $chromeArgs -Wait -NoNewWindow -PassThru

Start-Sleep -Seconds 3

if (Test-Path $pdfFile) {
    $pdfSize = (Get-Item $pdfFile).Length / 1KB
    
    Write-Host ""
    Write-Host "========================================" -ForegroundColor Green
    Write-Host "✓ PDF CREATED SUCCESSFULLY!" -ForegroundColor Green
    Write-Host "========================================" -ForegroundColor Green
    Write-Host "File: $pdfFile" -ForegroundColor Cyan
    Write-Host "Size: $([math]::Round($pdfSize, 2)) KB" -ForegroundColor Cyan
    Write-Host "Type: Basic (No AI Analysis)" -ForegroundColor Yellow
    Write-Host ""
    
    # Clean up HTML file
    Remove-Item $htmlFile -Force
    
    # Open PDF
    Write-Host "Opening PDF..." -ForegroundColor Yellow
    Start-Process $pdfFile
} else {
    Write-Host "ERROR: PDF generation failed" -ForegroundColor Red
    exit 1
}
