# Basic Terraform Plan Parser (No AI)
# Extracts raw data without intelligent analysis

param(
    [string]$PlanFile = "planQC20NovGN-output.txt",
    [string]$OutputMd = "Terraform_Plan_Basic_Report.md"
)

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Basic Terraform Plan Parser (No AI)" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Read the plan file
$planContent = Get-Content $PlanFile -Raw

# Extract plan summary
if ($planContent -match 'Plan: (\d+) to add, (\d+) to change, (\d+) to destroy') {
    $toAdd = $matches[1]
    $toChange = $matches[2]
    $toDestroy = $matches[3]
} else {
    $toAdd = 0
    $toChange = 0
    $toDestroy = 0
}

Write-Host "Found: $toAdd to add, $toChange to change, $toDestroy to destroy" -ForegroundColor Yellow

# Extract resource changes
$changes = @()
$lines = $planContent -split "`n"

$currentResource = $null
$currentAction = $null
$currentChanges = @()

foreach ($line in $lines) {
    # Detect resource blocks
    if ($line -match '^\s*#\s+(.+?)\s+will be (created|destroyed|updated in-place|replaced)') {
        # Save previous resource if exists
        if ($currentResource) {
            $changes += @{
                Resource = $currentResource
                Action = $currentAction
                Changes = $currentChanges -join "`n"
            }
        }
        
        $currentResource = $matches[1]
        $currentAction = $matches[2]
        $currentChanges = @()
    }
    # Detect attribute changes
    elseif ($line -match '^\s*[~\+\-]\s+(.+)') {
        if ($currentResource) {
            $currentChanges += $line.Trim()
        }
    }
}

# Add last resource
if ($currentResource) {
    $changes += @{
        Resource = $currentResource
        Action = $currentAction
        Changes = $currentChanges -join "`n"
    }
}

Write-Host "Extracted $($changes.Count) resource changes" -ForegroundColor Yellow

# Generate basic markdown report
$markdown = @"
# Terraform Plan Report (Basic)

**Generated:** $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")  
**Plan File:** $PlanFile

---

## Summary

| Metric | Count |
|--------|-------|
| Resources to Add | $toAdd |
| Resources to Change | $toChange |
| Resources to Destroy | $toDestroy |
| **Total Changes** | $($toAdd + $toChange + $toDestroy) |

---

## Resource Changes

"@

# Add each change
$changeNum = 1
foreach ($change in $changes) {
    $actionIcon = switch ($change.Action) {
        "created" { "➕" }
        "destroyed" { "❌" }
        "updated in-place" { "🔄" }
        "replaced" { "🔁" }
        default { "📝" }
    }
    
    $markdown += @"

### $changeNum. $actionIcon $($change.Action.ToUpper()) - $($change.Resource)

**Action:** $($change.Action)

**Resource Name:** ``$($change.Resource)``

"@

    if ($change.Changes) {
        $markdown += @"

**Changes:**
``````
$($change.Changes)
``````

"@
    }
    
    $changeNum++
}

# Add footer
$markdown += @"

---

## Notes

This is a **basic report** generated by parsing Terraform plan output.

- ✅ Extracted resource names and actions
- ✅ Listed attribute changes
- ❌ No impact analysis
- ❌ No risk assessment
- ❌ No recommendations
- ❌ No dependency analysis

**For detailed analysis with AI:**
- Risk assessment
- Impact analysis
- Deployment recommendations
- Rollback procedures
- Testing checklists

Use the AI-enhanced version of this tool.

---

**Report Type:** Basic (No AI)  
**Parser Version:** 1.0  
**Generation Time:** $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
"@

# Save markdown
$markdown | Out-File -FilePath $OutputMd -Encoding UTF8

Write-Host "✓ Markdown report created: $OutputMd" -ForegroundColor Green
Write-Host ""
